completed javascript-data-model - Fredrick Rana
fredrickrana/c0522-code-solutions pull request #27
Opened 2022-05-18 13:21 UTC by fredrickrana

![Screen Shot 2022-05-18 at 6 20 03 AM](https://user-images.githubusercontent.com/103611252/169048639-6c6edd5d-7054-451d-ab9b-effdbaaa5e8c.png)

2022-05-18 17:50 UTC, codingcodymiller requested changes

2022-05-18 17:50 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +];
Your structure for storing the data for this order is completely different from the rest of your order objects. If you tried to use this data in an actual application, it would cause major bugs. Your structure needs to be consistent between every order

2022-05-29 23:38 UTC, fredrickrana commented
![Screen Shot 2022-05-29 at 4 35 20 PM](https://user-images.githubusercontent.com/103611252/170895832-18536f2a-95d4-48d9-bf40-04d990c8948a.png)
Revised structure to be the same as the rest of the order objects. Added items array for consistency in storing data within all orders.

2022-05-30 16:09 UTC, codingcodymiller approved these changes

2022-05-30 17:37 UTC, merged