completed css-ecommerce-page - Fredrick Rana
fredrickrana/c0522-code-solutions pull request #39
Opened 2022-05-24 14:05 UTC by fredrickrana

![Screen Shot 2022-05-24 at 6 56 13 AM](https://user-images.githubusercontent.com/103611252/170055062-f639f3f0-a6ff-4770-99a6-a241d7ff3162.png)

2022-05-24 16:20 UTC, codingcodymiller requested changes

2022-05-24 16:20 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +}
Remember not to pollute your layout classes. Any additional styling outside of the proper styling for your layout classes should be applied to other classes you can add to the element in addition to the basic `column` class (only `flex-basis` or `width`) or `row` class (only `display: flex`)

2022-05-29 20:16 UTC, fredrickrana commented
![Screen Shot 2022-05-29 at 1 09 03 PM](https://user-images.githubusercontent.com/103611252/170889688-02c8f3e8-2df3-48fe-b177-7047ecb76fe0.png)
Restructured css layout classes by only applying proper styling to row and column classes. Applied the rest of the styling to other classes/elements.

2022-05-30 17:16 UTC, codingcodymiller approved these changes
Nice work!

2022-05-30 17:39 UTC, merged